/*
 * This source file was generated by the Gradle 'init' task
 */
package bytejam.project;

import bytejam.project.turbo.Window;

public class App {
    public static void main(String[] args) {
        Window window = Window.get();
        window.run();
    }
}